"""booking and client

Revision ID: 192691c585e4
Revises: 2e29d3e83f20
Create Date: 2025-12-09 00:06:53.171440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192691c585e4'
down_revision: Union[str, Sequence[str], None] = '2e29d3e83f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('businessId', sa.UUID(), nullable=False),
    sa.Column('fullName', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['businessId'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('businessId', sa.UUID(), nullable=False),
    sa.Column('staffId', sa.UUID(), nullable=True),
    sa.Column('serviceId', sa.UUID(), nullable=True),
    sa.Column('clientId', sa.UUID(), nullable=True),
    sa.Column('clientName', sa.String(length=150), nullable=False),
    sa.Column('clientPhone', sa.String(length=50), nullable=False),
    sa.Column('clientEmail', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('startTime', sa.Time(), nullable=False),
    sa.Column('endTime', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['businessId'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clientId'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['serviceId'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('clients')
    # ### end Alembic commands ###
