"""name en user

Revision ID: 2e29d3e83f20
Revises: 92a01fc9688f
Create Date: 2025-11-30 22:02:20.328441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e29d3e83f20'
down_revision: Union[str, Sequence[str], None] = '92a01fc9688f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_users', sa.Column('name', sa.String(length=150), server_default='default', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_users', 'name')
    # ### end Alembic commands ###
