"""creating all tables

Revision ID: 92a01fc9688f
Revises: 327d53321583
Create Date: 2025-11-23 23:43:05.872193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92a01fc9688f'
down_revision: Union[str, Sequence[str], None] = '327d53321583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_opening_hours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('businessId', sa.UUID(), nullable=False),
    sa.Column('dayOfWeek', sa.Integer(), nullable=False),
    sa.Column('openTime', sa.Time(), nullable=True),
    sa.Column('closeTime', sa.Time(), nullable=True),
    sa.Column('isClosed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['businessId'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('businessId', sa.UUID(), nullable=False),
    sa.Column('bookingId', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=150), nullable=False),
    sa.Column('templateKey', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('errorMessage', sa.String(length=500), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['businessId'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('businessId', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('durationMinutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['businessId'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('businessId', sa.UUID(), nullable=False),
    sa.Column('displayName', sa.String(length=150), nullable=False),
    sa.Column('photoUrl', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('sortOrder', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['businessId'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_schedule_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staffId', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('isDayOff', sa.Boolean(), nullable=True),
    sa.Column('startTime', sa.Time(), nullable=True),
    sa.Column('endTime', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['staffId'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staffId', sa.UUID(), nullable=False),
    sa.Column('serviceId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['serviceId'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staffId'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staffId', 'serviceId', name='uq_staff_service')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_services')
    op.drop_table('staff_schedule_overrides')
    op.drop_table('staff')
    op.drop_table('services')
    op.drop_table('notification_logs')
    op.drop_table('business_opening_hours')
    # ### end Alembic commands ###
